CC		=gcc
FLAG	=-Wall -Wextra -Werror
FILES	=$(shell find . -type f -name "*.c")
OBJ		=-o ft_display_file
CLR		=rm -rf ft_display_file

all:
	${CC} ${FLAG} ${FILES} ${OBJ}

clean:
	${CLR}

fclean:
	make clean